<?php
/**
 * Created by PhpStorm.
 * User: tangjun
 * Date: 2015/12/17
 * Time: 11:30
 */


$data = [
    0=>[
        'moduleid'=>'msc',
        'name'=>'资源管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'现有资源',
                'url'=>'/msc/admin/resources-manager/resources-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'新增资源',
                'url'=>'/msc/admin/resources-manager/add-resources',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            2=>[
                'moduleid'=>'msc',
                'name'=>'资源类别管理',
                'url'=>'/msc/admin/resources-manager/resources-cate-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    1=>[
        'moduleid'=>'msc',
        'name'=>'课程管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'课程安排',
                'url'=>'/msc/admin/courses/normal-courses-plan',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'培训安排',
                'url'=>'/msc/admin/training/add-training',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            2=>[
                'moduleid'=>'msc',
                'name'=>'课程监管',
                'url'=>'/msc/admin/courses/class-observe',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    2=>[
        'moduleid'=>'msc',
        'name'=>'设备外借归还管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'审核申请',
                'url'=>'/msc/admin/resources-manager/wait-examine-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'现有外借设备',
                'url'=>'/msc/admin/resources-manager/borrowed-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            2=>[
                'moduleid'=>'msc',
                'name'=>'外借历史',
                'url'=>'/msc/admin/resources-manager/borrow-record-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    3=>[
        'moduleid'=>'msc',
        'name'=>'开放实验室管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'审核申请',
                'url'=>'/msc/admin/lab/open-lab-apply-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'已审核申请',
                'url'=>'/msc/admin/lab/open-lab-apply-examined-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            2=>[
                'moduleid'=>'msc',
                'name'=>'使用历史',
                'url'=>'/msc/admin/lab/openlab-history-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    4=>[
        'moduleid'=>'msc',
        'name'=>'突发事件管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'突发事件审核申请',
                'url'=>'/msc/admin/lab/urgent-apply-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    5=>[
        'moduleid'=>'msc',
        'name'=>'开放设备管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'设备预约审核管理',
                'url'=>'/msc/admin/lab-tools/open-lab-tools-apply-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'已预约设备',
                'url'=>'/msc/admin/lab-tools/open-lab-tools-examined-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            2=>[
                'moduleid'=>'msc',
                'name'=>'设备预约使用历史',
                'url'=>'/msc/admin/lab-tools/open-lab-tools-use-history',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    6=>[
        'moduleid'=>'msc',
        'name'=>'学生信息审核',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'学生注册审核',
                'url'=>'/msc/admin/verify/student',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'教师注册审核',
                'url'=>'/msc/admin/verify/teacher',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ]
        ]
    ],
    7=>[
        'moduleid'=>'msc',
        'name'=>'用户权限管理',
        'url'=>'',
        'pid'=>'0',
        'ico'=>'',
        'order'=>'',
        'descrition'=>'',
        'child'=>[
            0=>[
                'moduleid'=>'msc',
                'name'=>'用户管理',
                'url'=>'/msc/admin/user/student-list',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
            1=>[
                'moduleid'=>'msc',
                'name'=>'角色权限管理',
                'url'=>'/auth/auth-manage',
                'pid'=>'0',
                'ico'=>'',
                'order'=>'',
                'descrition'=>''
            ],
        ]
    ],
];
//dfsafasdfas
https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxeeb197e3dee3357d&redirect_uri=http%3A%2F%2Fopenlab.hx.misrobot.com%2Fmsc%2Fwechat%2Flaboratory%2Flaboratory-list&response_type=code&scope=snsapi_base&state=123#wechat_redirect