<?php
namespace database;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class ResourcesLabSeeder123 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ResourcesClassroom =   new  \Modules\Msc\Entities\ResourcesClassroom();
        foreach($this->defaultData() as $input)
        {
                $ResourcesClassroom ->addLabResource($input);
        }
    }
    public function defaultData(){
        return array (
            0 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--13',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '代码',
                ),
            1 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--15',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '1',
                ),
            2 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--17',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '2',
                ),
            3 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--19',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            4 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--22',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            5 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--24',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            6 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--26',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            7 =>
                array (
                    'floor' => '3楼',
                    'code' => '3--28',
                    'name' => '临床技能室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            8 =>
                array (
                    'floor' => '4楼',
                    'code' => 4001,
                    'name' => '模拟手术室',
                    'area' => 35,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            9 =>
                array (
                    'floor' => '4楼',
                    'code' => 4002,
                    'name' => '模拟手术室',
                    'area' => 45,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            10 =>
                array (
                    'floor' => '4楼',
                    'code' => 4003,
                    'name' => '基本生命支持训练室',
                    'area' => 100,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            11 =>
                array (
                    'floor' => '4楼',
                    'code' => 4004,
                    'name' => '监控室',
                    'area' => 5,
                    'type' => '2',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            12 =>
                array (
                    'floor' => '4楼',
                    'code' => 4005,
                    'name' => '气道控制训练室',
                    'area' => 35,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            13 =>
                array (
                    'floor' => '4楼',
                    'code' => 4006,
                    'name' => '创伤急救训练室',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            14 =>
                array (
                    'floor' => '4楼',
                    'code' => 4017,
                    'name' => '数字化综合训练室',
                    'area' => 75,
                    'type' => '1',
                    'manager_name' => '赵蓉',
                    'typeCode' => '',
                ),
            15 =>
                array (
                    'floor' => '4楼',
                    'code' => 4018,
                    'name' => '全科医学综合训练室',
                    'area' => 75,
                    'type' => 1,
                    'manager_name' => '马俊荣',
                    'typeCode' => '',
                ),
            16 =>
                array (
                    'floor' => '4楼',
                    'code' => 4019,
                    'name' => '内镜诊疗技术训练室',
                    'area' => 185,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            17 =>
                array (
                    'floor' => '4楼',
                    'code' => 4022,
                    'name' => '眼科手术技能训练室',
                    'area' => 105,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            18 =>
                array (
                    'floor' => '4楼',
                    'code' => 4036,
                    'name' => '基本技能训练室3',
                    'area' => 64,
                    'type' => '1',
                    'manager_name' => '马俊荣',
                    'typeCode' => '',
                ),
            19 =>
                array (
                    'floor' => '4楼',
                    'code' => 4038,
                    'name' => '基本技能训练室2',
                    'area' => 71,
                    'type' => '1',
                    'manager_name' => '马俊荣',
                    'typeCode' => '',
                ),
            20 =>
                array (
                    'floor' => '4楼',
                    'code' => 4040,
                    'name' => '心肺腹听诊触诊实验室',
                    'area' => 60,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            21 =>
                array (
                    'floor' => '4楼',
                    'code' => 4041,
                    'name' => '心肺听诊实验室',
                    'area' => 20,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            22 =>
                array (
                    'floor' => '5楼',
                    'code' => 5001,
                    'name' => '模拟病房1',
                    'area' => 100,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            23 =>
                array (
                    'floor' => '5楼',
                    'code' => 5002,
                    'name' => '无菌技术训练室',
                    'area' => 100,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            24 =>
                array (
                    'floor' => '5楼',
                    'code' => 5004,
                    'name' => '模拟病房2',
                    'area' => 25,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            25 =>
                array (
                    'floor' => '5楼',
                    'code' => 5013,
                    'name' => '准备间',
                    'area' => 40,
                    'type' => '2',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            26 =>
                array (
                    'floor' => '5楼',
                    'code' => 5014,
                    'name' => '示教室1',
                    'area' => 40,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            27 =>
                array (
                    'floor' => '5楼',
                    'code' => 5015,
                    'name' => '示教室2',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            28 =>
                array (
                    'floor' => '5楼',
                    'code' => 5016,
                    'name' => '生物力学研究室',
                    'area' => 150,
                    'type' => '1',
                    'manager_name' => '骨科',
                    'typeCode' => '',
                ),
            29 =>
                array (
                    'floor' => '5楼',
                    'code' => 5017,
                    'name' => '伤口技能实验室',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            30 =>
                array (
                    'floor' => '5楼',
                    'code' => 5018,
                    'name' => '护理学实验室',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            31 =>
                array (
                    'floor' => '5楼',
                    'code' => 5032,
                    'name' => '儿科技能训练室',
                    'area' => 20,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            32 =>
                array (
                    'floor' => '5楼',
                    'code' => 5033,
                    'name' => '老年护理实验室',
                    'area' => 40,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            33 =>
                array (
                    'floor' => '5楼',
                    'code' => 5034,
                    'name' => '形体训练室',
                    'area' => 60,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            34 =>
                array (
                    'floor' => '5楼',
                    'code' => 5035,
                    'name' => '妇产科技能训练室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            35 =>
                array (
                    'floor' => '5楼',
                    'code' => 5036,
                    'name' => '妇儿综合训练室',
                    'area' => 30,
                    'type' => '1',
                    'manager_name' => '张超',
                    'typeCode' => '',
                ),
            36 =>
                array (
                    'floor' => '6楼',
                    'code' => 6001,
                    'name' => 'OT 康复实验室',
                    'area' => 63,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            37 =>
                array (
                    'floor' => '6楼',
                    'code' => 6002,
                    'name' => 'OT康复实验室',
                    'area' => 63,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            38 =>
                array (
                    'floor' => '6楼',
                    'code' => 6003,
                    'name' => 'PT康复实验室',
                    'area' => 134,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            39 =>
                array (
                    'floor' => '6楼',
                    'code' => 6015,
                    'name' => '眼视光学实验室',
                    'area' => 73,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            40 =>
                array (
                    'floor' => '6楼',
                    'code' => 6017,
                    'name' => '眼视光学实验室',
                    'area' => 37,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            41 =>
                array (
                    'floor' => '6楼',
                    'code' => 6019,
                    'name' => '眼视光学实验室',
                    'area' => 73,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            42 =>
                array (
                    'floor' => '6楼',
                    'code' => 6022,
                    'name' => '眼视光学实验室',
                    'area' => 70,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            43 =>
                array (
                    'floor' => '6楼',
                    'code' => 6024,
                    'name' => '营养膳食实验室',
                    'area' => 77,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            44 =>
                array (
                    'floor' => '6楼',
                    'code' => 6037,
                    'name' => '自主开放实验室2',
                    'area' => 40,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            45 =>
                array (
                    'floor' => '6楼',
                    'code' => 6038,
                    'name' => '自主开放实验室1',
                    'area' => 40,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            46 =>
                array (
                    'floor' => '6楼',
                    'code' => 6039,
                    'name' => '呼吸治疗实验室',
                    'area' => 92,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            47 =>
                array (
                    'floor' => '6楼',
                    'code' => 6040,
                    'name' => '医技影像超声检查学',
                    'area' => 69,
                    'type' => '1',
                    'manager_name' => '何霄',
                    'typeCode' => '',
                ),
            48 =>
                array (
                    'floor' => '7楼',
                    'code' => 7024,
                    'name' => '教学准备室',
                    'area' => 55,
                    'type' => '2',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            49 =>
                array (
                    'floor' => '7楼',
                    'code' => 7007,
                    'name' => '功能实验室',
                    'area' => 85,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            50 =>
                array (
                    'floor' => '7楼',
                    'code' => 7008,
                    'name' => '功能实验室',
                    'area' => 85,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            51 =>
                array (
                    'floor' => '7楼',
                    'code' => 7006,
                    'name' => '综合实验室',
                    'area' => 35,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            52 =>
                array (
                    'floor' => '7楼',
                    'code' => 7023,
                    'name' => '仪器室1',
                    'area' => 55,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            53 =>
                array (
                    'floor' => '7楼',
                    'code' => 7021,
                    'name' => '仪器室2',
                    'area' => 55,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            54 =>
                array (
                    'floor' => '7楼',
                    'code' => 7020,
                    'name' => '仪器室3',
                    'area' => 55,
                    'type' => '1',
                    'manager_name' => '赵清江',
                    'typeCode' => '',
                ),
            55 =>
                array (
                    'floor' => '8楼',
                    'code' => 8022,
                    'name' => '第一形态学实验室',
                    'area' => 50,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            56 =>
                array (
                    'floor' => '8楼',
                    'code' => 8021,
                    'name' => '第二形态学实验室',
                    'area' => 50,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            57 =>
                array (
                    'floor' => '8楼',
                    'code' => 8020,
                    'name' => '第三形态学实验室',
                    'area' => 50,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            58 =>
                array (
                    'floor' => '8楼',
                    'code' => 8018,
                    'name' => '第四形态学实验室',
                    'area' => 50,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            59 =>
                array (
                    'floor' => '8楼',
                    'code' => 8017,
                    'name' => '标本陈列馆',
                    'area' => 100,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            60 =>
                array (
                    'floor' => '8楼',
                    'code' => 8007,
                    'name' => '标本示教室',
                    'area' => 70,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            61 =>
                array (
                    'floor' => '8楼',
                    'code' => 8008,
                    'name' => '标本制作室',
                    'area' => 50,
                    'type' => 2,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            62 =>
                array (
                    'floor' => '8楼',
                    'code' => 8006,
                    'name' => '教学准备室',
                    'area' => 50,
                    'type' => 2,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            63 =>
                array (
                    'floor' => '8楼',
                    'code' => 8019,
                    'name' => '多人共览显微镜室',
                    'area' => 15,
                    'type' => 1,
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            64 =>
                array (
                    'floor' => '10楼',
                    'code' => 10003,
                    'name' => '虚拟仿真实验室',
                    'area' => 120,
                    'type' => '1',
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            65 =>
                array (
                    'floor' => '10楼',
                    'code' => 10002,
                    'name' => '示教室',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '熊茂琦',
                    'typeCode' => '',
                ),
            66 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01027',
                    'name' => '手术准备实验室',
                    'area' => 28,
                    'type' => '2',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            67 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01025',
                    'name' => '手术实验室1',
                    'area' => 28,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            68 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01023',
                    'name' => '手术实验室2',
                    'area' => 28,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            69 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01021',
                    'name' => '手术实验室3',
                    'area' => 36,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            70 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01019',
                    'name' => '手术实验室4',
                    'area' => 36,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            71 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01017',
                    'name' => '手术实验室5',
                    'area' => 36,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            72 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01016',
                    'name' => '动物准备间',
                    'area' => 32,
                    'type' => '2',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            73 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01018',
                    'name' => '强生微创实验室1',
                    'area' => 60,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            74 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01020',
                    'name' => '',
                    'area' => '',
                    'type' => '',
                    'manager_name' => '',
                    'typeCode' => '',
                ),
            75 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01022',
                    'name' => '奥林巴斯微创、内镜实验室',
                    'area' => 50,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            76 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01024',
                    'name' => '',
                    'area' => '',
                    'type' => '',
                    'manager_name' => '',
                    'typeCode' => '',
                ),
            77 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01026',
                    'name' => '奥林巴斯模拟实验室',
                    'area' => 28,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            78 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01040',
                    'name' => '男更衣间',
                    'area' => 20,
                    'type' => '2',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            79 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01041',
                    'name' => '女更衣间',
                    'area' => 20,
                    'type' => '2',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            80 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01038',
                    'name' => '办公室',
                    'area' => 32,
                    'type' => '2',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            81 =>
                array (
                    'floor' => '负一楼',
                    'code' => 'b01039',
                    'name' => '视教室',
                    'area' => 80,
                    'type' => '1',
                    'manager_name' => '岳中伟',
                    'typeCode' => '',
                ),
            82 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--13',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            83 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--15',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            84 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--17',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            85 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--19',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            86 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--22',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            87 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--24',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            88 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--26',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            89 =>
                array (
                    'name' => '临床技能室',
                    'code' => '3--28',
                    'location' => '新八教3楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            90 =>
                array (
                    'name' => '模拟手术室',
                    'code' => '4001',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            91 =>
                array (
                    'name' => '模拟手术室',
                    'code' => '4002',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            92 =>
                array (
                    'name' => '基本生命支持训练室',
                    'code' => '4003',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            93 =>
                array (
                    'name' => '监控室',
                    'code' => '4004',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            94 =>
                array (
                    'name' => '气道控制训练室',
                    'code' => '4005',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            95 =>
                array (
                    'name' => '创伤急救训练室',
                    'code' => '4006',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            96 =>
                array (
                    'name' => '数字化综合训练室',
                    'code' => '4017',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵蓉',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            97 =>
                array (
                    'name' => '全科医学综合训练室',
                    'code' => '4018',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '马俊荣',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            98 =>
                array (
                    'name' => '内镜诊疗技术训练室',
                    'code' => '4019',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            99 =>
                array (
                    'name' => '眼科手术技能训练室',
                    'code' => '4022',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            100 =>
                array (
                    'name' => '基本技能训练室3',
                    'code' => '4036',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '马俊荣',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            101 =>
                array (
                    'name' => '基本技能训练室2',
                    'code' => '4038',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '马俊荣',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            102 =>
                array (
                    'name' => '心肺腹听诊触诊实验室',
                    'code' => '4040',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            103 =>
                array (
                    'name' => '心肺听诊实验室',
                    'code' => '4041',
                    'location' => '新八教4楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            104 =>
                array (
                    'name' => '模拟病房1',
                    'code' => '5001',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            105 =>
                array (
                    'name' => '无菌技术训练室',
                    'code' => '5002',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            106 =>
                array (
                    'name' => '模拟病房2',
                    'code' => '5004',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            107 =>
                array (
                    'name' => '准备间',
                    'code' => '5013',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            108 =>
                array (
                    'name' => '示教室1',
                    'code' => '5014',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            109 =>
                array (
                    'name' => '示教室2',
                    'code' => '5015',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            110 =>
                array (
                    'name' => '生物力学研究室',
                    'code' => '5016',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '骨科',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            111 =>
                array (
                    'name' => '伤口技能实验室',
                    'code' => '5017',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            112 =>
                array (
                    'name' => '护理学实验室',
                    'code' => '5018',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            113 =>
                array (
                    'name' => '儿科技能训练室',
                    'code' => '5032',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            114 =>
                array (
                    'name' => '老年护理实验室',
                    'code' => '5033',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            115 =>
                array (
                    'name' => '形体训练室',
                    'code' => '5034',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            116 =>
                array (
                    'name' => '妇产科技能训练室',
                    'code' => '5035',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            117 =>
                array (
                    'name' => '妇儿综合训练室',
                    'code' => '5036',
                    'location' => '新八教5楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '张超',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            118 =>
                array (
                    'name' => 'OT 康复实验室',
                    'code' => '6001',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            119 =>
                array (
                    'name' => 'OT康复实验室',
                    'code' => '6002',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            120 =>
                array (
                    'name' => 'PT康复实验室',
                    'code' => '6003',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            121 =>
                array (
                    'name' => '眼视光学实验室',
                    'code' => '6015',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            122 =>
                array (
                    'name' => '眼视光学实验室',
                    'code' => '6017',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            123 =>
                array (
                    'name' => '眼视光学实验室',
                    'code' => '6019',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            124 =>
                array (
                    'name' => '眼视光学实验室',
                    'code' => '6022',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            125 =>
                array (
                    'name' => '营养膳食实验室',
                    'code' => '6024',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            126 =>
                array (
                    'name' => '自主开放实验室2',
                    'code' => '6037',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            127 =>
                array (
                    'name' => '自主开放实验室1',
                    'code' => '6038',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            128 =>
                array (
                    'name' => '呼吸治疗实验室',
                    'code' => '6039',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            129 =>
                array (
                    'name' => '医技影像超声检查学',
                    'code' => '6040',
                    'location' => '新八教6楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '何霄',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            130 =>
                array (
                    'name' => '教学准备室',
                    'code' => '7024',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            131 =>
                array (
                    'name' => '功能实验室',
                    'code' => '7007',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            132 =>
                array (
                    'name' => '功能实验室',
                    'code' => '7008',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            133 =>
                array (
                    'name' => '综合实验室',
                    'code' => '7006',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            134 =>
                array (
                    'name' => '仪器室1',
                    'code' => '7023',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            135 =>
                array (
                    'name' => '仪器室2',
                    'code' => '7021',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            136 =>
                array (
                    'name' => '仪器室3',
                    'code' => '7020',
                    'location' => '新八教7楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '赵清江',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            137 =>
                array (
                    'name' => '第一形态学实验室',
                    'code' => '8022',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            138 =>
                array (
                    'name' => '第二形态学实验室',
                    'code' => '8021',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            139 =>
                array (
                    'name' => '第三形态学实验室',
                    'code' => '8020',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            140 =>
                array (
                    'name' => '第四形态学实验室',
                    'code' => '8018',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            141 =>
                array (
                    'name' => '标本陈列馆',
                    'code' => '8017',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            142 =>
                array (
                    'name' => '标本示教室',
                    'code' => '8007',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            143 =>
                array (
                    'name' => '标本制作室',
                    'code' => '8008',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            144 =>
                array (
                    'name' => '教学准备室',
                    'code' => '8006',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            145 =>
                array (
                    'name' => '多人共览显微镜室',
                    'code' => '8019',
                    'location' => '新八教8楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            146 =>
                array (
                    'name' => '虚拟仿真实验室',
                    'code' => '10003',
                    'location' => '新八教10楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            147 =>
                array (
                    'name' => '示教室',
                    'code' => '10002',
                    'location' => '新八教10楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '熊茂琦',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            148 =>
                array (
                    'name' => '手术准备实验室',
                    'code' => 'b01027',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            149 =>
                array (
                    'name' => '手术实验室1',
                    'code' => 'b01025',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            150 =>
                array (
                    'name' => '手术实验室2',
                    'code' => 'b01023',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            151 =>
                array (
                    'name' => '手术实验室3',
                    'code' => 'b01021',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            152 =>
                array (
                    'name' => '手术实验室4',
                    'code' => 'b01019',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            153 =>
                array (
                    'name' => '手术实验室5',
                    'code' => 'b01017',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            154 =>
                array (
                    'name' => '动物准备间',
                    'code' => 'b01016',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            155 =>
                array (
                    'name' => '强生微创实验室1',
                    'code' => 'b01018',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            156 =>
                array (
                    'name' => '',
                    'code' => 'b01020',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            157 =>
                array (
                    'name' => '奥林巴斯微创、内镜实验室',
                    'code' => 'b01022',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            158 =>
                array (
                    'name' => '',
                    'code' => 'b01024',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            159 =>
                array (
                    'name' => '奥林巴斯模拟实验室',
                    'code' => 'b01026',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            160 =>
                array (
                    'name' => '男更衣间',
                    'code' => 'b01040',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            161 =>
                array (
                    'name' => '女更衣间',
                    'code' => 'b01041',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            162 =>
                array (
                    'name' => '办公室',
                    'code' => 'b01038',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
            163 =>
                array (
                    'name' => '视教室',
                    'code' => 'b01039',
                    'location' => '新八教负一楼',
                    'begintime' => '08:00:00',
                    'endtime' => '22:00:00',
                    'opened' => 0,
                    'manager_name' => '岳中伟',
                    'manager_mobile' => '',
                    'detail' => '',
                ),
        );
    }
}
