--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/1/13 10:46:54
-- Server version: 5.7.10
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE osce_mis;

--
-- Definition for table area
--
DROP TABLE IF EXISTS area;
CREATE TABLE area (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '名称',
  code VARCHAR(32) DEFAULT NULL COMMENT '代码',
  cate VARCHAR(32) NOT NULL COMMENT '类别',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试区域'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table bbs_topic
--
DROP TABLE IF EXISTS bbs_topic;
CREATE TABLE bbs_topic (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(256) NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '内容',
  pid INT(11) DEFAULT 0 COMMENT '父id',
  level INT(11) DEFAULT 0 COMMENT '层级',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '讨论区_主题'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table cases
--
DROP TABLE IF EXISTS cases;
CREATE TABLE cases (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) DEFAULT NULL COMMENT '名称',
  code VARCHAR(32) DEFAULT NULL COMMENT '代码',
  description VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '病例(考试内容)'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table config
--
DROP TABLE IF EXISTS config;
CREATE TABLE config (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL COMMENT '名称',
  cate VARCHAR(255) DEFAULT NULL COMMENT '类别',
  type VARCHAR(255) NOT NULL COMMENT '类型',
  value TEXT NOT NULL COMMENT '配置值',
  description VARCHAR(255) DEFAULT NULL COMMENT '配置说明',
  created_at DATETIME NOT NULL,
  updated_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_unicode_ci
COMMENT = '系统配置表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam
--
DROP TABLE IF EXISTS exam;
CREATE TABLE exam (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  code VARCHAR(32) DEFAULT NULL COMMENT '考试代码',
  name VARCHAR(64) DEFAULT NULL COMMENT '考试名称',
  begin_dt DATETIME DEFAULT NULL COMMENT '开始时间',
  end_dt DATETIME DEFAULT NULL COMMENT '结束时间',
  status TINYINT(1) DEFAULT NULL COMMENT '当前状态',
  total INT(11) DEFAULT NULL COMMENT '总人数',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  description TEXT DEFAULT NULL COMMENT '描述',
  sequence_cate TINYINT(1) NOT NULL DEFAULT 1 COMMENT '排序方式',
  sequence_mode TINYINT(2) NOT NULL DEFAULT 1 COMMENT '考试排序模式',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table flows
--
DROP TABLE IF EXISTS flows;
CREATE TABLE flows (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '名称',
  description TEXT DEFAULT NULL COMMENT '备注',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试流程'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table inform_training
--
DROP TABLE IF EXISTS inform_training;
CREATE TABLE inform_training (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(64) NOT NULL COMMENT '名称',
  address VARCHAR(64) DEFAULT NULL COMMENT '地点',
  begin_dt DATETIME DEFAULT NULL COMMENT '开始时间',
  end_dt DATETIME DEFAULT NULL COMMENT '结束时间',
  teacher VARCHAR(64) DEFAULT NULL COMMENT '讲师',
  content TEXT DEFAULT NULL COMMENT '内容',
  attachments TEXT DEFAULT NULL COMMENT '附件url地址数组',
  status TINYINT(1) DEFAULT 1 COMMENT '状态',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  description TEXT DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '培训通知'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table pad
--
DROP TABLE IF EXISTS pad;
CREATE TABLE pad (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  code VARCHAR(32) NOT NULL COMMENT '设备代码',
  name VARCHAR(32) DEFAULT NULL COMMENT '名称',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'PAD信息表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table room
--
DROP TABLE IF EXISTS room;
CREATE TABLE room (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '名称',
  nfc VARCHAR(32) DEFAULT NULL COMMENT 'NFC代码',
  address VARCHAR(64) DEFAULT NULL COMMENT '位置',
  code VARCHAR(32) DEFAULT NULL COMMENT '房间编码',
  create_user_id INT(11) DEFAULT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  description TEXT DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '房间'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table student
--
DROP TABLE IF EXISTS student;
CREATE TABLE student (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '姓名',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  user_id INT(11) NOT NULL DEFAULT 0 COMMENT '用户编号',
  idcard VARCHAR(32) NOT NULL COMMENT '身份证号码',
  mobile VARCHAR(11) NOT NULL COMMENT '手机号码',
  code VARCHAR(32) DEFAULT NULL COMMENT '学号',
  avator VARCHAR(128) DEFAULT NULL COMMENT '照片',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考生'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table subject
--
DROP TABLE IF EXISTS subject;
CREATE TABLE subject (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  title VARCHAR(255) DEFAULT NULL COMMENT '标题',
  score TINYINT(4) NOT NULL COMMENT '满分',
  sort TINYINT(4) DEFAULT NULL COMMENT '序号',
  status TINYINT(1) NOT NULL COMMENT '状态',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  description TEXT DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试项目'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table teacher
--
DROP TABLE IF EXISTS teacher;
CREATE TABLE teacher (
  id INT(11) NOT NULL COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '姓名',
  code VARCHAR(32) DEFAULT NULL COMMENT '工号',
  type TINYINT(1) NOT NULL COMMENT '类型',
  case_id INT(11) DEFAULT NULL COMMENT '病例编号',
  status TINYINT(1) NOT NULL COMMENT '状态',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '教师'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table vcr
--
DROP TABLE IF EXISTS vcr;
CREATE TABLE vcr (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) NOT NULL COMMENT '名称',
  code VARCHAR(32) DEFAULT NULL COMMENT '代码',
  ip VARCHAR(16) NOT NULL COMMENT 'IP地址',
  username VARCHAR(32) NOT NULL COMMENT '用户名',
  password VARCHAR(64) NOT NULL COMMENT '密码',
  port INT(11) NOT NULL COMMENT '端口',
  channel VARCHAR(32) NOT NULL COMMENT '通道',
  description TEXT DEFAULT NULL COMMENT '备注',
  status TINYINT(4) DEFAULT NULL COMMENT '状态',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '摄像机信息表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table watch
--
DROP TABLE IF EXISTS watch;
CREATE TABLE watch (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  code VARCHAR(32) NOT NULL COMMENT '设备代码',
  name VARCHAR(32) DEFAULT NULL COMMENT '名称',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态',
  description VARCHAR(255) DEFAULT NULL COMMENT '备注',
  factory VARCHAR(255) DEFAULT NULL COMMENT '生产厂家',
  sp VARCHAR(255) DEFAULT NULL COMMENT '规格',
  create_user_id INT(11) DEFAULT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 1638
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '腕表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table area_vcr
--
DROP TABLE IF EXISTS area_vcr;
CREATE TABLE area_vcr (
  id INT(11) NOT NULL COMMENT '编号',
  area_id INT(11) DEFAULT NULL COMMENT '区域_编号',
  vcr_id INT(11) DEFAULT NULL COMMENT '摄像机_编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_32 FOREIGN KEY (area_id)
    REFERENCES area(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_33 FOREIGN KEY (vcr_id)
    REFERENCES vcr(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试区域-摄像机关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_flow
--
DROP TABLE IF EXISTS exam_flow;
CREATE TABLE exam_flow (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  flow_id INT(11) NOT NULL COMMENT '流程编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_48 FOREIGN KEY (flow_id)
    REFERENCES flows(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_49 FOREIGN KEY (exam_id)
    REFERENCES exam(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试-流程关联表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_flow_room
--
DROP TABLE IF EXISTS exam_flow_room;
CREATE TABLE exam_flow_room (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  serialnumber INT(11) NOT NULL COMMENT '序号',
  room_id INT(11) NOT NULL COMMENT '房间编号',
  flow_id INT(11) NOT NULL COMMENT '流程编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_exam_flow_room_room_id FOREIGN KEY (room_id)
    REFERENCES room(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_53 FOREIGN KEY (flow_id)
    REFERENCES flows(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试流程-房间关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_room
--
DROP TABLE IF EXISTS exam_room;
CREATE TABLE exam_room (
  id INT(11) NOT NULL COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  room_id INT(11) NOT NULL COMMENT '房间编号',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_exam_room_room_id FOREIGN KEY (room_id)
    REFERENCES room(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_47 FOREIGN KEY (exam_id)
    REFERENCES exam(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试房间关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_screening
--
DROP TABLE IF EXISTS exam_screening;
CREATE TABLE exam_screening (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  begin_dt DATETIME DEFAULT NULL COMMENT '开始时间',
  end_dt DATETIME DEFAULT NULL COMMENT '结束时间',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '当前状态',
  sort INT(11) DEFAULT 0 COMMENT '序号',
  total INT(11) DEFAULT 0 COMMENT '人数',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  nfc_tag VARCHAR(64) DEFAULT NULL COMMENT 'nfc标签',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_4 FOREIGN KEY (exam_id)
    REFERENCES exam(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试考场关系表(考试场次表)'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table inform_info
--
DROP TABLE IF EXISTS inform_info;
CREATE TABLE inform_info (
  id INT(11) NOT NULL COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  name VARCHAR(64) NOT NULL COMMENT '名称',
  accept VARCHAR(32) NOT NULL COMMENT '接收人角色',
  content TEXT DEFAULT NULL COMMENT '内容',
  attachments TEXT DEFAULT NULL COMMENT '附件url地址数组',
  status TINYINT(1) DEFAULT 1 COMMENT '状态',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_56 FOREIGN KEY (exam_id)
    REFERENCES exam(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '资讯通知'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table room_vcr
--
DROP TABLE IF EXISTS room_vcr;
CREATE TABLE room_vcr (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  room_id INT(11) NOT NULL COMMENT '房间_编号',
  vcr_id INT(11) NOT NULL COMMENT '摄像机_编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_11 FOREIGN KEY (vcr_id)
    REFERENCES vcr(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_room_vcr_room_id FOREIGN KEY (room_id)
    REFERENCES room(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '房间-摄像机关联表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table standard
--
DROP TABLE IF EXISTS standard;
CREATE TABLE standard (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  subject_id INT(11) DEFAULT NULL COMMENT '考试项目编号',
  content TEXT DEFAULT NULL COMMENT '标准内容',
  sort TINYINT(4) DEFAULT NULL COMMENT '序号',
  score TINYINT(4) DEFAULT NULL COMMENT '分值',
  pid INT(11) DEFAULT 0 COMMENT '父编号',
  level INT(11) DEFAULT 0 COMMENT '层级',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  answer TEXT DEFAULT NULL COMMENT '参考答案',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_3 FOREIGN KEY (subject_id)
    REFERENCES subject(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '评分标准'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table station
--
DROP TABLE IF EXISTS station;
CREATE TABLE station (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  name VARCHAR(32) DEFAULT NULL COMMENT '名称',
  code VARCHAR(32) DEFAULT NULL COMMENT '编码',
  type TINYINT(4) NOT NULL COMMENT '考站类型',
  description VARCHAR(255) DEFAULT NULL COMMENT '描述',
  subject_id INT(11) NOT NULL COMMENT '考试项目编号',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  mins INT(11) NOT NULL DEFAULT 0 COMMENT '标准考试时间(分钟)',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_34 FOREIGN KEY (subject_id)
    REFERENCES subject(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考站'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table watch_log
--
DROP TABLE IF EXISTS watch_log;
CREATE TABLE watch_log (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  watch_id INT(11) NOT NULL COMMENT '腕表编号',
  action VARCHAR(32) NOT NULL COMMENT '动作类型',
  context TEXT DEFAULT NULL COMMENT '当前上下文(序列化)',
  student_id INT(11) DEFAULT 0 COMMENT '绑定学生编号',
  create_user_id INT(11) DEFAULT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_55 FOREIGN KEY (watch_id)
    REFERENCES watch(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_watch_log_student_id FOREIGN KEY (student_id)
    REFERENCES student(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '腕表使用历史'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_flow_station
--
DROP TABLE IF EXISTS exam_flow_station;
CREATE TABLE exam_flow_station (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '编号',
  serialnumber INT(11) NOT NULL COMMENT '序号',
  station_id INT(11) NOT NULL COMMENT '考站编号',
  flow_id INT(11) NOT NULL COMMENT '流程编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_exam_flow_station_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_46 FOREIGN KEY (flow_id)
    REFERENCES flows(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试流程-考站关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_plan
--
DROP TABLE IF EXISTS exam_plan;
CREATE TABLE exam_plan (
  id INT(11) NOT NULL COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  exam_screening_id INT(11) NOT NULL COMMENT '场次编号',
  student_id INT(11) NOT NULL COMMENT '考生编号',
  station_id INT(11) NOT NULL COMMENT '考站编号',
  room_id INT(11) NOT NULL COMMENT '房间编号',
  begin_dt DATETIME NOT NULL COMMENT '开始时间',
  end_dt DATETIME DEFAULT NULL COMMENT '结束时间',
  status TINYINT(1) DEFAULT NULL COMMENT '状态',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_exam_plan_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试计划'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_queue
--
DROP TABLE IF EXISTS exam_queue;
CREATE TABLE exam_queue (
  id INT(11) NOT NULL COMMENT '编号',
  exam_id INT(11) NOT NULL COMMENT '考试编号',
  exam_screening_id INT(11) NOT NULL COMMENT '场次编号',
  student_id INT(11) NOT NULL COMMENT '考生编号',
  station_id INT(11) NOT NULL COMMENT '考站编号',
  room_id INT(11) NOT NULL COMMENT '房间编号',
  begin_dt DATETIME NOT NULL COMMENT '开始时间',
  end_dt DATETIME DEFAULT NULL COMMENT '结束时间',
  status TINYINT(1) DEFAULT NULL COMMENT '状态',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_exam_queue_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试队列'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_screening_student
--
DROP TABLE IF EXISTS exam_screening_student;
CREATE TABLE exam_screening_student (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  exam_screening_id INT(11) NOT NULL COMMENT '考试场次编号',
  student_id INT(11) NOT NULL COMMENT '考生编号',
  is_notity TINYINT(1) NOT NULL DEFAULT 0 COMMENT '已通知',
  is_signin TINYINT(1) NOT NULL DEFAULT 0 COMMENT '已签到',
  is_end TINYINT(1) NOT NULL DEFAULT 0 COMMENT '考试场次终止',
  signin_dt DATETIME DEFAULT NULL COMMENT '签到时间',
  watch_id INT(11) DEFAULT NULL COMMENT '腕表编号',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_20 FOREIGN KEY (student_id)
    REFERENCES student(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_21 FOREIGN KEY (exam_screening_id)
    REFERENCES exam_screening(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_22 FOREIGN KEY (watch_id)
    REFERENCES watch(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试场次-学生关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table invite
--
DROP TABLE IF EXISTS invite;
CREATE TABLE invite (
  id INT(11) NOT NULL COMMENT '编号',
  name VARCHAR(64) NOT NULL COMMENT '名称',
  begin_dt DATETIME NOT NULL COMMENT '开始时间',
  end_dt DATETIME NOT NULL COMMENT '结束时间',
  exam_screening_id INT(11) NOT NULL COMMENT '考试场次编号',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_41 FOREIGN KEY (exam_screening_id)
    REFERENCES exam_screening(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'sp老师邀请'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table room_station
--
DROP TABLE IF EXISTS room_station;
CREATE TABLE room_station (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  room_id INT(11) NOT NULL COMMENT '房间编号',
  station_id INT(11) NOT NULL COMMENT '考站编号',
  create_user_id INT(11) DEFAULT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_room_station_room_id FOREIGN KEY (room_id)
    REFERENCES room(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_room_station_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '房间-考站关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table station_case
--
DROP TABLE IF EXISTS station_case;
CREATE TABLE station_case (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  case_id INT(11) NOT NULL COMMENT '病例_编号',
  station_id INT(11) NOT NULL COMMENT '考站_编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_7 FOREIGN KEY (case_id)
    REFERENCES cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_station_case_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考站-病例关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table station_teacher
--
DROP TABLE IF EXISTS station_teacher;
CREATE TABLE station_teacher (
  id INT(11) NOT NULL COMMENT '编号',
  station_id INT(11) NOT NULL COMMENT '考站_编号',
  user_id INT(11) NOT NULL COMMENT '教师_编号',
  case_id INT(11) DEFAULT NULL COMMENT '病例_编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  type TINYINT(1) NOT NULL DEFAULT 1 COMMENT '类型',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_35 FOREIGN KEY (case_id)
    REFERENCES cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_37 FOREIGN KEY (user_id)
    REFERENCES teacher(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_station_teacher_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考站-老师关系表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table station_vcr
--
DROP TABLE IF EXISTS station_vcr;
CREATE TABLE station_vcr (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  station_id INT(11) NOT NULL COMMENT '考站_编号',
  vcr_id INT(11) NOT NULL COMMENT '录像机_编号',
  created_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_12 FOREIGN KEY (vcr_id)
    REFERENCES vcr(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_station_vcr_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考站-摄像机关联表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table test_result
--
DROP TABLE IF EXISTS test_result;
CREATE TABLE test_result (
  id INT(11) NOT NULL COMMENT '编号',
  student_id INT(11) NOT NULL COMMENT '考生编号',
  exam_screening_id INT(11) NOT NULL COMMENT '场次编号',
  station_id INT(11) NOT NULL COMMENT '考站编号',
  begin_dt DATETIME NOT NULL COMMENT '考试开始时间',
  end_dt DATETIME NOT NULL COMMENT '考试结束时间',
  time INT(11) DEFAULT NULL COMMENT '用时',
  score INT(11) NOT NULL COMMENT '最终成绩',
  score_dt DATETIME NOT NULL COMMENT '评分时间',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  teacher_id INT(11) NOT NULL COMMENT '评分人编号',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_23 FOREIGN KEY (student_id)
    REFERENCES student(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_24 FOREIGN KEY (exam_screening_id)
    REFERENCES exam_screening(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_36 FOREIGN KEY (teacher_id)
    REFERENCES teacher(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_test_result_station_id FOREIGN KEY (station_id)
    REFERENCES station(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试结果记录表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_score
--
DROP TABLE IF EXISTS exam_score;
CREATE TABLE exam_score (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  exam_result_id INT(11) NOT NULL COMMENT '考试结果编号',
  subject_id INT(11) NOT NULL COMMENT '考核项目编号',
  standard_id INT(11) NOT NULL COMMENT '评分标准编号',
  score TINYINT(4) DEFAULT NULL COMMENT '分值',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_27 FOREIGN KEY (exam_result_id)
    REFERENCES test_result(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_28 FOREIGN KEY (subject_id)
    REFERENCES subject(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_29 FOREIGN KEY (standard_id)
    REFERENCES standard(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考核评分详情'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table exam_sp_teacher
--
DROP TABLE IF EXISTS exam_sp_teacher;
CREATE TABLE exam_sp_teacher (
  id INT(11) NOT NULL COMMENT '编号',
  invite_id INT(11) DEFAULT NULL COMMENT '邀请编号',
  exam_screening_id INT(11) NOT NULL COMMENT '考试场次编号',
  case_id INT(11) DEFAULT NULL COMMENT '病例编号',
  teacher_id INT(11) NOT NULL COMMENT '教师编号',
  create_user_id INT(11) NOT NULL COMMENT '创建人',
  created_at DATETIME DEFAULT NULL COMMENT '创建时间',
  updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (id),
  CONSTRAINT FK_Reference_38 FOREIGN KEY (invite_id)
    REFERENCES invite(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_39 FOREIGN KEY (exam_screening_id)
    REFERENCES exam(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Reference_40 FOREIGN KEY (teacher_id)
    REFERENCES teacher(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '考试-sp老师关系表'
ROW_FORMAT = DYNAMIC;

-- An error occurred while generating script for objects of type 'Triggers':
-- Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.t1.EVENT_OBJECT_SCHEMA' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;