<?php
/**
 * Created by PhpStorm.
 * @author tangjun <tangjun@misrobot.com>
 * @date 2016-01-04 11:19
 * @copyright 2013-2015 MIS misrobot.com Inc. All Rights Reserved
 */

namespace Modules\Msc\Http\Controllers\WeChat;
use Modules\Msc\Entities\Student;
use Modules\Msc\Entities\Teacher;
use Modules\Msc\Http\Controllers\MscWeChatController;
use Illuminate\Http\Request;
use Modules\Msc\Entities\Laboratory;
class LaboratoryCotroller extends MscWeChatController
{

    /**
     * @param Student $student
     * @param Teacher $teacher
     * @author tangjun <tangjun@misrobot.com>
     * @date    2016年1月4日12:05:39
     * @copyright 2013-2015 MIS misrobot.com Inc. All Rights Reserved
     */
    public function  __construct(Student $student, Teacher $teacher)
    {
        parent::__construct($student, $teacher); // TODO: Change the autogenerated stub
        $this->Laboratory = new Laboratory;
    }


    /**
     * 待预约列表
     * @method  GET
     * @url /msc/wechat/laboratory-list
     * @access public
     * @param Request $Request
     * @return \Illuminate\View\View
     * @author tangjun <tangjun@misrobot.com>
     * @date    2016年1月4日12:05:39
     * @copyright 2013-2015 MIS misrobot.com Inc. All Rights Reserved
     */
    public function LaboratoryList(Request $Request){
        $LaboratoryList = [];
        return view();
    }

    /**
     * 获取普通实验室列表
     * @method GET
     * @url /msc/wechat/laboratory-list-data
     * @access public
     * @DateTime 时间（筛选预约的时间）
     * @return \Illuminate\Http\JsonResponse
     * @author tangjun <tangjun@misrobot.com>
     * @date
     * @copyright 2013-2015 MIS misrobot.com Inc. All Rights Reserved
     */
    public function LaboratoryListData(){
        $data = [];
        $this->Laboratory;
        return response()->json(
            $this->success_rows(1,'获取成功',$data->total(),20,$data->currentPage(),array('ClassroomApplyList'=>$data))
        );
    }
    /**
     * 获取开放实验室列表
     * @method GET
     * @url /msc/wechat/open-laboratory-list-data
     * @access public
     * @DateTime 时间（筛选预约的时间）
     * @return \Illuminate\Http\JsonResponse
     * @author tangjun <tangjun@misrobot.com>
     * @date    2016年1月4日15:46:29
     * @copyright 2013-2015 MIS misrobot.com Inc. All Rights Reserved
     */
    public function OpenLaboratoryListData(){
        $data = [];
        return response()->json(
            $this->success_rows(1,'获取成功',$data->total(),20,$data->currentPage(),array('ClassroomApplyList'=>$data))
        );
    }
}